### ISSUE TITLE
Weekrow from previous month displayed even if no days of the current months are displayed.

### ISSUE THREAD

**Issue by n3o77** [mattlewis92/calendar-utils#13]
I have the problem that I want to render only the weekdays (mon - fri). If the 1. of the selected month falls on sat or sun `getMonthView` still returns the whole week of the last month.

<img width="505" alt="screen shot 2017-06-15 at 23 28 17" src="https://user-images.githubusercontent.com/321891/27202552-575df304-5222-11e7-8f6a-3248a1c8cf98.png">

I'm not sure if that's really a bug or not. If it is I can probably provide a PR in the next few days to fix this but I wanted to check for thoughts or input on this behaviour first.

Thank you.

**Comment by mattlewis92** [comment]
I'd say this is a bug as it looks obviously broken from a users point of view. It should be simple enough to write a failing test and fix the behaviour, if you'd like to make a PR that's be great 😀

**Comment by n3o77** [comment]
@mattlewis92 awesome, huge thanks for taking care of that!

**Comment by mattlewis92** [comment]
No worries, I've just released `0.0.53` with the fix. Thanks for reporting! 😄
