### ISSUE TITLE
CalendarEvent Schema

### ISSUE THREAD

**Issue by manibonthu** [mattlewis92/calendar-utils#17]
How can I change CalendarEvent Schema.
Can you please help to solve this issue.

I want schema like this 

title :string,
start : date,
end : date,
myevents : [{name :string,startDate : date, endDate : date}]

is it possible to create schema like this.
Thanks In Advance.

**Comment by mattlewis92** [comment]
You can use the meta property for this

**Comment by elvnthaus** [comment]
Could you link me to documentation of how to use meta properties, meta types. Not sure how to implement them correctly.

If I wanted to extend the CalendarEvent interface would I create another interface (Visit.ts):

Visit.ts
```
export interface Visit {
  service: string,
  pets: String[],
  fees: {
    isAfterHours?: boolean,
    isWeekend?: boolean,
    isHoliday?: boolean
    isLateNotice?: boolean
  }
}

```

and then import it into a file and add it as a type after the type CalendarEvent?

```
events: CalendarEvent<Visit>[] = []
```
