### ISSUE TITLE
Error: No provider for CalendarUtils!

### ISSUE THREAD

**Issue by ihoudjedje** [mattlewis92/calendar-utils#18]
I'm using [this tutorial](https://thielcole.github.io/ionic2/2017/02/03/Ionic2-Calendar.html) which based on [your calendar project](https://github.com/mattlewis92/angular-calendar) to have calendar integrated into my ionic 2 app, and I'm running into this error which i think it has something to do with this repo.

how can i solve it plz? is it something like : npm i @CalendarUtils ?

**Comment by mattlewis92** [comment]
I think you're missing the forRoot call on the module import. Make sure you're calling `CalendarModule.forRoot()` when importing the module.
