### ISSUE TITLE
Issue with typescript version

### ISSUE THREAD

**Issue by R-iskey** [mattlewis92/calendar-utils#20]
Hi, I think I got error with Typescript 2.6.1 version. Please check screenshot
![image](https://user-images.githubusercontent.com/12074147/33714146-60043cb0-db67-11e7-9c7f-38e951d22bc0.png)

**Comment by mattlewis92** [comment]
Those errors occur if you're using an old version of TS, you need to be using >= 2.3. `npm ls typescript` to check
