### ISSUE TITLE
Usage with Angular 4 is impossible

### ISSUE THREAD

**Issue by MatteoJoliveau** [mattlewis92/calendar-utils#21]
This repository requires TypeScript 2.5 but it is used in your [angular-calendar](https://github.com/mattlewis92/angular-calendar) component which uses Angular 4 (and therefore TS < 2.4). This is giving us a lot of problems since you used some features of TS 2.4+ (like string-based enums) and we are not able to compile the project anymore.  
It works when using TS 2.4 but since the Angular Team does not recommend its usage with NG 4 we really can't use it (this is a commercial project that should go into production soon and cannot afford to have potentially incompatible software).

Can you please fix this or tell us how to keep using your (btw awesome) component with NG 4/TS 2.3?
![image](https://user-images.githubusercontent.com/9077612/34295823-ac6c6a60-e70f-11e7-870b-de4b81e1c6fd.png)

**Comment by mattlewis92** [comment]
Hi there, ah I forgot string based enums were a TS 2.4 feature, undoing it now would be a breaking change though. The only thing I can recommend is to either use 0.21.x of `angular-calendar` which doesn't include this change, upgrade TS to 2.4 (I have been using all 2.x version of TS with our ng4 app at work and have experienced no problems with it) or upgrade angular to v5 which officially supports TS 2.4 (should just be a case of changing your package.json to v5 providing you've dealt with all v2 deprecation warnings). Hope that helps!

**Comment by MatteoJoliveau** [comment]
Hey, thanks for the quick response.
We actually tried a workaround by commenting the problematic enum in calendar-utils and it seems to work (provided we never encounter a case where this enum is needed, but being it an error message enum we hope to be able to deal with them anyway).
We cannot migrate to Angular 5 for now, but it's planned for the next milestone so we'll keep that in mind. If we have too many problems until then we'll switch to calendar 0.21 and then wait for the NG 5 migration.

Thanks for the help!

**Comment by mattlewis92** [comment]
Hey there, I looked at this with a fresh pair of eyes today and found a way of restoring TS 2.3 compatibility in a non breaking way. Please give 0.22.2 of `angular-calendar` a go and it should work again. So sorry about that! 😄

**Comment by MatteoJoliveau** [comment]
Hey, that's good news! We'll give it a spin when we come back to work in january. Thanks a lot for the effort in helping us!
