### ISSUE TITLE
Universal

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [mattlewis92/calendar-utils#24]
Hello,

I've got an error in univeral mode:

> C:\development\norboxportal\node_modules\calendar-utils\bundles\calendar-utils.umd.js:10
})(window, function() {
   ^

> ReferenceError: window is not defined

Since it is a dependency of angular-calendar, it breaks my app.

Thank you in advance!

**Comment by mattlewis92** [comment]
Thanks for reporting, this should be fixed in `0.2.1`, if you uninstall and re-install `angular-calendar` it should pull in the new version. Please let me know if that works for you! 😄

**Comment by ssi-hu-tasi-norbert** [comment]
It seems ok. Thank you for your quick fix.

**Comment by ssi-hu-tasi-norbert** [comment]
After removing and adding again works, however I've tried a fresh install with yarn and it downloaded the previous version, so pls. add this version to the angular-calendar before releasing the next version. Thank you!

**Comment by mattlewis92** [comment]
If you clean the [yarn cache](https://yarnpkg.com/lang/en/docs/cli/cache/) it should do the trick, but I'll cut a new version soon with the upgrade.
