### ISSUE TITLE
Request to Add name attribute to EventColor

### ISSUE THREAD

**Issue by riyadali** [mattlewis92/calendar-utils#26]
I am allowing custom color schemes to be associated with events.  In order to implement this, I needed to have a color scheme name affiliated with the primary and secondary colors.  This helps in the UI because it allows the user to select the color scheme by name and to also create custom ones and assign a name to it so that they can use it for other events.

This is what my interface looks like
```
export interface ColorScheme {  
  id?: number;
  // color schemes with no owners are the default color schemes
  owner?: number;
  name: string; 
  /* may eventually want to explictly type these as "Color" --
     refer to this link for a start https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/color/color-tests.ts
  */
  primary: string;
  secondary: string;
}
```

I was wondering if you could support adding a name to the EventColor interface.  I am having an issue when going from the CalendarEvent to my local object that is displayed on the UI.  Without the "name" field I would have no idea what color scheme is associated with that particular event.  I have a workaround in that I could stuff the ColorScheme name in the meta data for the CalendarEvent but it seems as if it would be more appropriate to have it defined explicitly under ColorEvent.

You can see this in action here (the first Calendar) https://stackblitz.com/github/riyadali/townofbabylon/tree/AddCalendarEditable

You'll need to register and login to site (so that you can access the update buttons for an event) ... use any made up email and password.  It may take some time to register initially since the service handling the login goes to sleep quite frequently.

There is no rush since I have a workaround. 

FYI... Listed below are my default color schemes based on the samples you provided

```
// Some default color schemes
  redColorScheme : ColorScheme = {
      id: 1,
      name: 'Red',
      primary: '#ad2121',
      secondary: '#FAE3E3'
  };

  yellowColorScheme : ColorScheme = {
      id: 2,
      name: 'Yellow',
      primary: '#e3bc08',
      secondary: '#FDF1BA'
  };
 
  blueColorScheme : ColorScheme = {
      id: 3,
      name: 'Blue',
      primary: '#1e90ff',
      secondary: '#D1E8FF'
  };
```

**Comment by mattlewis92** [comment]
Hey there, I'm a bit loathe to just add random property names to typings that don't actually serve a purpose in the main calendar (in face, in my own app I actually have a 3rd color property, yet I still wouldn't add it here), but you have a couple ways to solve this without changing anything here, you can either use the event meta property to hold this information:

```
{
  start: startOfDay(new Date()),
  title: 'An event with no end date',
  color: {
    primary: '#e3bc08',
    secondary: '#FDF1BA'
  },
  meta: {
     colorName: 'yello'
  }
},
```

Or you can extend the interface and create your own:

```
interface ColorScheme extends EventColor {
  name: string;
}

interface MyCalendarEvent extends CalendarEvent {
  color: ColorScheme;
}
```

Hope that helps! 😄

**Comment by riyadali** [comment]
Hello,

Thanks.  I tend to agree with you about adding random properties.  I was
able to get around this so no worries. I like the flexibility afforded in
that one is able to extend the CalendarEvent interface using the meta
property.  Perhaps if you do a major rework at some point you may want to
add a meta property to all your interfaces, including EventColor. In my
implementation, I needed to save all of my extraneous color property in the
CalendarEvent meta field and then do some transforms (i.e. copying from the
EventColor meta data to the "color" attribute) when going from the UI  to
my local classes.  If the EventColor had a meta attribute, I would not need
my own separate unique class that is very similar to the EventColor, and I
would not need to do the extra transforms because the data is only saved in
one place.

I considered something similar to what you suggested in terms of having
ColorScheme extending EventColor.  The issue with this is that although you
can save ColorScheme directly into EventColor, the reverse is not true.  So
when trying to capture changes made in the UI, extra processing would be
needed to also copy the other color attributes in the various Event meta
property, whereas if the meta property was defined in EventColor itself it
would just be a simple copy from the UI's EventColor with the appropriate
meta properties set [the binding in the UI is done on these meta
properties] to my local version of EventColor with no additional changes
needed for the meta information.

But as I indicated, it's not a big deal since I do have a work around.

Riyad
