### ISSUE TITLE
Events placed in the wrong position when moving to and from DST

### ISSUE THREAD

**Issue by julian-jelfs** [mattlewis92/calendar-utils#27]
Hi, this is a bit of a nasty one. Lets say that I have two events occurring as follows: 

start "2019-10-26T03:00:00Z"
start "2019-10-27T03:00:00Z"

These two events are plotted in the same position even though they represent different times to the user. Specifically the second event is plotted in the wrong place. This is because the we change (in the uk) from DST on the 27th of October at 2am. What this mean is that specifically for that day - the 27th of October we cannot use the number of minutes from the start of the day to calculate position because one of the hours effectively happens twice. 

Very happy to try to help with this but I'm not sure whether you have any thoughts on what the correct solution is?

**Comment by julian-jelfs** [comment]
I _think_ that it needs to do something like this inside the getDayView function: 

```
      if (eventStart > startOfView) {
        const endOffset = eventStart.getTimezoneOffset();
        const startOffset = startOfView.getTimezoneOffset();
        const diff = startOffset - endOffset;
        top += differenceInMinutes(eventStart, startOfView) + diff;
      }
```

so if the start of the day has a different offset to the start of the event we account for that when calculating the diff. This seems to correct the particular problem that I can see but I'm not sure whether a) it will have any knock on effects or b) whether a similar fix will need to be applied in other places.

**Comment by mattlewis92** [comment]
If you [force the calendar](https://github.com/mattlewis92/calendar-utils/issues/28#issuecomment-511141261) into UTC mode it should fix the issue you described, but if that patch does fix it without having to operate in UTC mode, that would be quite nice (although it may cause other problems / not fix everything). Do you want to send a PR here with that fix and then we'll see where we land? I think it's safe to add, as it will only affect days with DST, as most times `diff` will always be 0.
