### ISSUE TITLE
Please Update date-fns

### ISSUE THREAD

**Issue by nkitku** [mattlewis92/calendar-utils#33]
Unable to build using webpack: Error: Can't resolve 'date-fns/set_year/index'
please update date-fns [new update](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#200---2019-08-20)

**Comment by mattlewis92** [comment]
I'm working on it! In the meantime you can make your own date adapter that uses v2 of date-fns as described here: https://github.com/mattlewis92/angular-calendar/issues/963#issuecomment-489318417

**Comment by MartinJHItInstituttet** [comment]
@mattlewis92 Thanks for the good work! Your patch solution is working perfectly.

**Comment by mattlewis92** [comment]
I just released `0.4.0` with the update, `angular-calendar` beta with the update coming shortly! 😄
