### ISSUE TITLE
Add Right-Side Space to Hour Segments Request

### ISSUE THREAD

**Issue by SyntakSoftware** [mattlewis92/calendar-utils#36]
I wanted to request a change that will affect this and the angular-calendar projects.  In order to allow the capture of a click/dblclick or the context menu, would you consider having the Events not take up 100% of the Day Column.

This functionality is present on the Angular Scheduler component from Syncfusion and others.
![Syncfusion Calendar Gap](https://user-images.githubusercontent.com/15039746/65259035-9b485000-dac9-11e9-8201-f7c1a6eebcab.png)

I have been able to adjust line 658 in the calendar-utils.ts file to:

`const width = 95 / columnCount;`

Changing the 100 to 95 to have the Events calculate to take up 95% of the column space on the Week View.  This allows for a right-click or, in my case, a double click on an hour segment in order to open a dialog for that time segment (even when that segment is full with Events).

![My Schedule with Gap](https://user-images.githubusercontent.com/15039746/65259474-5670e900-daca-11e9-9051-1f2cba6eee0f.png)

If a change like this wound not have unintended consequences, this would be a great functionality add.  Thanks for the consideration.

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue, you can actually do this with a few lines of CSS in your global stylesheet (I do it in my own app as well)

```
.cal-week-view .cal-time-events .cal-day-column {
    margin-right: 5px;
  }

  .cal-week-view .cal-hour {
    width: calc(100% + 5px);
  }
```

Demo here: https://stackblitz.com/edit/angular-d891nx?file=index.html

Let me know if that works for you 😄

**Comment by SyntakSoftware** [comment]
Works Perfectly!  Thanks so much!
Could I suggest that you maybe also have this on your "kitchen sink" example?  I would have grabbed it from there for sure!

Thanks again!

**Comment by mattlewis92** [comment]
Actually it probably makes sense to just include this by default for everyone, I made a task: https://github.com/mattlewis92/angular-calendar/issues/1097
