### ISSUE TITLE
Incorrect endOfView

### ISSUE THREAD

**Issue by ajmonfue** [mattlewis92/calendar-utils#40]
Hi,
the `endOfView` variable of the 23rd hour and 59th minute shouldn't be 23:59:59?, with the current implementation being 23:59:00.
https://github.com/mattlewis92/calendar-utils/blob/a1fd4541056fa840e1fd87bf3e2c807a193f90be/src/calendar-utils.ts#L944

#### Suggested change
```js
const endOfView: Date = setMinutes(
    setHours(endOfDay(viewDate), sanitiseHours(dayEnd.hour)),
    sanitiseMinutes(dayEnd.minute)
  );
```

**Comment by mattlewis92** [comment]
Hey, thanks for reporting, I just fixed this in `0.7.2`, let me know if it works ok for you 😄
