### ISSUE TITLE
Missing DayView export

### ISSUE THREAD

**Issue by notsure** [mattlewis92/calendar-utils#42]
Hi,

I'm facing a update problem where an export statement is now missing.

With this commit, the DayView Interface is no longer exported. If there are no bigger impacts it would be nice to fix this.

https://github.com/mattlewis92/calendar-utils/commit/a23983f8d58e98a2e13e0f0060da8b15de3ff455

**Comment by mattlewis92** [comment]
Hey there, with that change the day and week view's are now the same (a day view is just a week view with 1 day duration). The replacement interface is [`WeekView`](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L81) and the old day view specific code is only an internal implementation detail now that will be removed in the near future as it's not very performant, hence why it's not exposed as the public api anymore. You should be able to do everything you did before with the old code with the replacements listed in that commit, let me know if you need and more guidance 😄
