### ISSUE TITLE
Where is the usage details? 

### ISSUE THREAD

**Issue by nehalahmed929** [mattlewis92/calendar-utils#45]
no info on npm about how to use this package

**Comment by mattlewis92** [comment]
Hey there, I never really got round to adding docs for this package and it's not something I really have time to do in the immediate future, but as the source is all written in typescript the best thing I can recommend right now is reading the source. The 2 main functions are [getWeekView](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L710-L729) and [getMonthView](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L793-L804).

**Comment by nehalahmed929** [comment]
Ok. I understand. no problem.
