### ISSUE TITLE
Rounding error in getDayView leads to consecutive events appearing as next to eachother

### ISSUE THREAD

**Issue by cypressious** [mattlewis92/calendar-utils#46]
I'm using the angular-calendar library and I've hit the following visual bug:

![grafik](https://user-images.githubusercontent.com/1191816/129225072-a8c894a8-4419-4d83-8668-d019b0d53095.png)

The event times are 8:10 - 8:15 and 8:15 - 8:20 so the events should not be displayed as overlapping. This only happens with some even times.

Debugging the code lead me to the `getDayView` method in which the `bottom` property of the first event seems to have a rounding error which leads to it being treated as if it overlaps with the second event.

![grafik](https://user-images.githubusercontent.com/1191816/129225399-c90f0141-41b8-406a-b7db-6118183fff46.png)
![grafik](https://user-images.githubusercontent.com/1191816/129225426-0335401d-fbed-4d23-946a-baa1d6440a33.png)

**Comment by mattlewis92** [comment]
Please could you make a pull request with a fix (or even just a failing test case). You can adapt a test case from [here](https://github.com/mattlewis92/calendar-utils/blob/master/test/calendar-utils-utc.spec.ts#L2725-L2755).

To run it locally you can checkout the repo and do `npm i` and then `npm start`. Let me know if you need any more help, thanks! 😄

**Comment by cypressious** [comment]
@mattlewis92 I've opened #47

**Comment by mattlewis92** [comment]
Released as `0.8.5`, thanks for your contribution! 😄  `npm update calendar-utils --depth=2` should allow you to upgrade it inside the calendar.

**Comment by cypressious** [comment]
Would it be possible to release a new version of angular-calendar with the updated transitive dependency?

**Comment by mattlewis92** [comment]
> Would it be possible to release a new version of angular-calendar with the updated transitive dependency?

It's already covered by the range here: https://github.com/mattlewis92/angular-calendar/blob/master/package.json#L163

So if you do `npm update calendar-utils --depth=2` it should update it 😄

**Comment by cypressious** [comment]
Awesome, thank you.
