### ISSUE TITLE
Add "timezoneOffset" to DateAdapter instead of getting it from the date object

### ISSUE THREAD

**Issue by Kleyguerth** [mattlewis92/calendar-utils#48]
I'm using a custom DateAdapter to force a specific timezone (in my case UTC without using momentjs), however, due to a few places in this module calling getTimezoneOffset directly from the date object, it breaks on days with a DST change.

Moving it to the DateAdapter will let the library consumer define a timezone.

**Comment by mattlewis92** [comment]
Sounds like a great idea, feel free to send a pull request!
