### ISSUE TITLE
WeekView - support for precise event-spanning

### ISSUE THREAD

**Issue by juzarevic** [mattlewis92/calendar-utils#7]
I'm using calendar-utils non-directly - I use it as dependency of [angular-calendar](https://mattlewis92.github.io/angular-calendar/) package (which is awesome, by the way).
My use-case is that I would like to have precise week view in a way that every event starts and ends in defined time. I successfully made that change in the code - in https://github.com/mattlewis92/calendar-utils/blob/master/src/calendarUtils.ts , line 135 became:
```javascript
        span = differenceInMinutes(event.end, begin)/1440.0;
```
and line 149 became:
```javascript
        const distance: number = differenceInMinutes(event.start, startOfWeek)/1440.0;
```
and everything works great. Now, I would like to know which are possibilities to add support for this type of week view in angular-calendar? Also, is there some reason behind calculating WeekView from start of day to end of day, instead calculating start and end of event?

Sorry for bad format, this is my first issuing ever.

EDIT: Of course, there is a probably better way than using magic constants in my solution, but as quick-fix, it works well for me.

**Comment by mattlewis92** [comment]
Hi there! Sorry I'm a bit confused about what you're trying to implement, the week view ignores event times as there's no scale on the view so the user wouldn't be able to gauge what the start and end time is from just looking at it:

<img width="963" alt="screen shot 2017-04-07 at 20 30 36" src="https://cloud.githubusercontent.com/assets/6425649/24816542/15653a7a-1bd1-11e7-8742-5a22aac356ff.png">

I could completely be misinterpreting what you mean though, would you be able to explain a bit more about what you're trying to implement, maybe with a rough sketch or something? Thanks! 😄

**Comment by juzarevic** [comment]
Hi! Thanks for fast response :smile: I hope you at least understand the line changes which I put into the issue. And here are the screenshots of angular-calendar with these changes applied (of course, locally).
First two screenshots show event data (each event start on 3pm and ends at 10am, next or some other day). I'm putting these screenshots so you can see how my events are defined.
Last screenshot shows WeekView, which shows events absolutely correctly after my modification mentioned before. So this is functionality which I want - with those light modifications I have made, I got that functionality.

I'm wondering why is this part implemented as it is and is there some clean way to override that behavior, since, for now, I literally changed these two lines in node_modules folder.

EDIT: Put less bloated images

![dayview-14-04](https://cloud.githubusercontent.com/assets/27018518/24817719/f41344cc-1bdd-11e7-9f77-7a84df73d099.png)
![dayview-15-04](https://cloud.githubusercontent.com/assets/27018518/24817717/f3e074c0-1bdd-11e7-8062-a8929a8fbf38.png)
![weekview](https://cloud.githubusercontent.com/assets/27018518/24817718/f4009106-1bdd-11e7-9d98-834b0ffc7161.png)

**Comment by mattlewis92** [comment]
Thanks for the screenshot - that helps a lot. Now I can actually see it implemented it's a lot different (and way better!) from how I thought it'd look in my head. I'm tempted to keep the old behaviour as opt in just in case there are some users that don't want this behaviour (also this lib is used for the angular 1 version which might break with this feature as the css for that version is pretty hacky). Would you like to make a pull request to this repo that adds your change, while keeping the old behaviour as opt in? If not I'm happy to do it, as you've already done the business logic 😀

**Comment by juzarevic** [comment]
Great! Only problem as I can see is that I'm not sure if I will be able to make the opt-in part (I didn't explored the library that well), but I will do my best in a day. And if I fail, I'll contact you so you can make the changes. So basically, you want me to make a new behavior default, but put some extra optional argument into the functions so user can change to old behavior, am I right? And this way, angular-calendar will use the new functionality since it becomes default?

**Comment by mattlewis92** [comment]
Yup that's correct! You should just need to pass a new Boolean option through the getWeekView function to the offset and span functions. If you throw together something basic to get started with I can review it and we can go from there 😀

**Comment by juzarevic** [comment]
I've created pull-request. But it failed! That's because of my lack of experience. On Travis, I saw it threw some error about too long lines. Can you please tell me which npm tasks should I run before pulling request? Thanks in advance :smiley:

**Comment by mattlewis92** [comment]
No problem, if you run 'npm start' it will run the tests and linter in watch mode, there's pretty good coverage so it should hopefully guide you enough, but let me know if you get stuck 😀

**Comment by juzarevic** [comment]
Ok, thanks :smiley: Now I see that it fails several tests, so I'll continue to play with it so next pull request will be tested. Keep in touch!

**Comment by juzarevic** [comment]
Now I see test results. And specification is logically different from what the new functionality brings in. First test is:
```typescript
it('should get the correct span, offset and extends values for events that start within the week', () => {

    const events: CalendarEvent[] = [{
      start: new Date('2016-06-27'),
      end: new Date('2016-06-29'),
      title: '',
      color: {primary: '', secondary: ''}
    }];

    const result: WeekViewEventRow[] = getWeekView({events, viewDate: new Date('2016-06-27'), weekStartsOn: 0});
    expect(result).to.deep.equal([{
      row: [{
        event: events[0],
        offset: 1,
        span: 3,
        startsBeforeWeek: false,
        endsAfterWeek: false
      }]
    }]);

  });
```
As you can see, test expects `span: 3`, but problem is that with new functionality span should be 2 (since difference 2016-06-27 00:00 and 2016-06-29 00:00 is really 2 days, not three). Now, what to do, alter the specification or something else? :smile:

**Comment by mattlewis92** [comment]
As we're keeping the old behaviour behind a flag, pass that through to the getWeekView function call which will confirm that the old behaviour still works. Then add some new tests that asserts the new behaviour (id probably just copy paste all the existing getWeekView tests and change the assertions to match the new behaviour)
